---
- hosts: all
  become: yes
  tasks:
    - name: install apache
      apt:
        name: apache2
        state: latest

    - name: create content
      copy:
        content: "<h1>apache installed through ansible playbook</h1>"
        dest: /var/www/html/index.html

    - name: restart apache
      service:
        name: apache2
        state: restarted

    - name: exec command
      shell: apt install net-tools
